version: '3'
services:
  database:
    image: "postgres:alpine"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "2345:5432"

volumes:
  database-data:
